### PR TITLE
Fixes to grammar

### PR DESCRIPTION
**Pull request by danielhers**
Handles the following cases, which would cause a failure before:
- Alignments may correspond to multiple tokens, e.g. `e.2,4`.
- Variables may also have alignments in case of co-reference.
- Negative numbers were causing a failure because the "-" would be matched by `NAMEDCONST`

### CODE REVIEW

**Comment by nschneid** [comment]
Thanks @danielhers! Sounds like this fixes #2.

Have you checked whether the code handling the alignments is compatible with the expanded definition of what can be aligned? I'm thinking particularly of https://github.com/nschneid/amr-hackathon/blob/master/src/amr.py#L384, where the variable and concept are rendered with an alignment, and subsequent code that attaches the aligned word in square brackets.

**Comment by danielhers** [comment]
@nschneid I verified that loading AMRs and writing to string still works the same, including with alignments, but I didn't thoroughly check all the functionality.

**Comment by nschneid** [comment]
OK, could you add a test case after https://github.com/nschneid/amr-hackathon/blob/master/src/amr.py#L218 that adds variable alignments and one-to-many alignments?

**Comment by danielhers** [comment]
I added one, hope it's not too long. Anyway, I'm afraid it fails:

    ValueError: invalid literal for int() with base 10: '3,4'

**Comment by nschneid** [comment]
OK, so this example shows a reentrant variable that is aligned (`p~e.17`). Is there reason to allow alignment to a variable preceding a concept, e.g. `p~e.17 / protein`? I believe the grammar allows it, but it might not be necessary.

**Comment by danielhers** [comment]
Thanks @nschneid , updated the PR with your commit :)

**Comment by danielhers** [comment]
The examples I have are from the [aligned Bio AMR corpus](http://amr.isi.edu/download/2016-03-14/alignment-release-training-bio.txt) available from [the AMR website](http://amr.isi.edu/download.html).

I did not find any such case as you said. This is what I did to search:

    egrep --color '\~e\.[0-9,]+ /' alignment-release-*-bio.txt

**Comment by danielhers** [comment]
@nschneid I fixed a problem with your commit and made some other minor fixes.

**Comment by danielhers** [comment]
@nschneid I also fixed the alignment of variables according to the observation that it should only be printed when `instance_fulfilled=False`.
Everything's working well now as far as I know.

**Comment by nschneid** [comment]
Awesome! One last thing: Could you modify the grammar to disallow alignments on the first occurrence of variables, since these are not handled by the string conversion code and appear to be unnecessary anyway?

One solution is to rewrite

    X = "(" ` VAR _ "/" _ CONCEPT (_ REL _ Y)* ` ")"
    Y = X / NAMEDCONST / VAR / STR / NUM

as

    X = "(" ` VAR _ "/" _ CONCEPT (_ REL _ Y)* ` ")"
    Y = X / ATOM ALIGNMENT?
    ATOM = NAMEDCONST / VAR / STR / NUM

and remove `ALIGNMENT?` from the RHS of `NAMEDCONST`, `VAR`, `STR`, and `NUM`.

**Comment by danielhers** [comment]
I tried your suggestion and it gave me:

    parsimonious.exceptions.IncompleteParseError: Rule 'rules' matched in its entirety, but it didn't consume all the text. The non-matching portion of the text begins with 'ALIGNMENT?
    ATOM = NA' (line 9, column 14).

**Comment by danielhers** [comment]
@nschneid fixed.

**Comment by nschneid** [comment]
Thanks again!

**Pull request merged**
